# Generated by Django 4.2.4 on 2023-08-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tittle", models.CharField(max_length=100)),
                ("discription", models.CharField(max_length=500)),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
